REGISTRATION_BUTTON = "//button[text() = 'Зарегистрироваться']"
LOGIN_BUTTON_ON_LOGIN_PAGE = "//button[text() = 'Войти']"
LOGIN_BUTTON_ON_MAIN_PAGE = "//button[text() = 'Войти в аккаунт']"
LOGIN_BUTTON_BY_HREF = "//a[@href = '/login']"
LOGOUT_BUTTON = "//button[text() = 'Выход']"
PROFILE_BUTTON = "//a[@href = '/account']"
BUN_TAB = "//div[span[text() = 'Булки']]"
SAUCE_TAB = "//div[span[text() = 'Соусы']]"
TOPPING_TAB = "//div[span[text() = 'Начинки']]"
INPUT_CONTAINER_FOR_PASSWORD = "(//div[contains(@class, 'input__container')])[last()]"
ERROR_MESSAGE = "//p[text() = 'Некорректный пароль']"